language: python

python:
    - "3.4"
    - "3.5"

build:
    ci:
        - apt-get update
        - apt-get install mediainfo
        - mkdir -p shippable/codecoverage
        - pip install --upgrade -e .
        - coverage run ./setup.py test
        - coverage xml --include 'video_utils*' -o shippable/codecoverage/coverage.xml
        - nosetests --with-xunit --xunit-file=shippable/testresults/nosetests.xml
